name: "✨ feature"
description: "feature 작업 사항을 입력해주세요."
title: "✨ [feat] "
body:
  - type: textarea
    attributes:
      label: 🚀 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 간결하게 적을수록 좋습니다!
    validations:
      required: true