name: "⚡ update"
description: "update 작업 사항을 입력해주세요."
title: "⚡ [update] "
body:
  - type: textarea
    attributes:
      label: ⚡ 설명
      description: 업데이트된 내용을 작성해 주세요.
      placeholder: 간결하게 적을수록 좋습니다!
    validations:
      required: true